Add angle method to calculate angle between two Vectors (issue #31)
3ptscience/vectormath pull request #32
Opened 2019-01-05 21:32 UTC by josephjcontreras

The angle method will calculate the angle between two
Vectors (both Vector2 or Vector3) and return the angle
either radians (default) or degrees

This is in response to issue #31.

2019-01-09 06:25 UTC, fwkoch requested changes
@josephjcontreras - This is great! Thank you so much for the contribution!

I have a few minor in-line comments, mostly about style tweaks. Biggest thing, though, can you please add tests for the `angle` method? No need for anything too fancy - just check that calculated angles are what you expect for a few different cases, and maybe make sure expected failures happen too. (Also, what if the length of one of the vectors is 0? Is a `DivideByZero` error fine? - maybe so, but we should probably document and test that case...)

2019-01-09 06:25 UTC, fwkoch commented on vectormath/vector.py
> +            return ang * 180 / np.pi
Looking at travis - there are a couple minor pylint issues. First is this unnecessary `else`/`return`; it can just be:
```python
        if unit == 'rad':
            return ang
        return ang * 180 / np.pi
```
Or possibly even cleaner with one return:
```python
        if unit == 'deg':
            ang = ang * 180 / np.pi
        return ang
```

2019-01-09 06:25 UTC, fwkoch commented on vectormath/vector.py
> +    def angle(self, vec=None):
Also from pylint, this call signature should just be the same as the other `angle` method.

2019-01-09 06:25 UTC, fwkoch commented on vectormath/vector.py
> +        """Angle between two vectors given in either radians ('rad') or degrees
Minor, but can you follow this for docstring convention: https://www.python.org/dev/peps/pep-0257/

Basically just one short descriptive line ("Calculate angle between two vectors"), line break, then details (i.e. info about the unit kwarg).

2019-01-09 06:25 UTC, fwkoch commented on vectormath/vector.py
> +            raise TypeError('Angle operand must be a vector')
Another picky comment but possibly this should be more specific (since you can't do angle between Vector2 and 3). Just like `'Angle operand must be a vector of class {}'.format(self.__class__.__name__)`? If that makes sense to you...

2019-01-09 06:25 UTC, fwkoch commented on vectormath/vector.py
> +        ang = np.arccos(self.dot(vec) / (self.length * vec.length))
👍

2019-01-10 04:51 UTC, josephjcontreras commented on vectormath/vector.py
> +            return ang * 180 / np.pi
I went with the second option, `if unit == 'deg': ...`

2019-01-10 04:52 UTC, josephjcontreras commented on vectormath/vector.py
> +            raise TypeError('Angle operand must be a vector')
Good idea. Updated error message to read `'Angle operand must be of class {}'                        .format(self.__class__.__name__)`, like you suggested.

2019-01-10 04:58 UTC, josephjcontreras commented on vectormath/vector.py
> +        """Angle between two vectors given in either radians ('rad') or degrees
Updated docstring to read


```
 """Calculate the angle between two Vectors

unit: unit for returned angle, either 'rad' or 'deg'. Defaults to 'rad'
"""
```

2019-01-10 05:12 UTC, josephjcontreras commented
@fwkoch Thanks for the feedback. I've updated the `angle` method per your comments to improve the docstring, linting, and error messages.

I also added the `ZeroDivisionError` you suggested for when one of the Vectors has a length of `0`.

Thanks,

2019-01-10 17:28 UTC, fwkoch approved these changes

2019-01-11 00:22 UTC, fwkoch commented
@josephjcontreras - this is looking great. Thanks for all your updates. Pretty sure the current travis failures are unrelated to your changes; I'll fix them up separately then get this merged.

2019-01-16 08:40 UTC, merged